# Generated by Django 4.2.6 on 2023-10-15 14:28

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="", editable=False, populate_from="title", unique=True
            ),
            preserve_default=False,
        ),
    ]
