# Generated by Django 4.2.6 on 2023-10-23 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_address_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_address', to='store.order'),
        ),
    ]
